# Generated by Django 5.1.7 on 2025-05-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
