# Generated by Django 5.1.7 on 2025-05-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_user_company_profile_user_type'),
        ('user', '0002_update_user_roles'),
    ]

    operations = [
    ]
