# Generated by Django 5.1.3 on 2025-05-20 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_by_hod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_created_staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("head_of_department", "HOD"),
                    ("ict", "ICT"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
